name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Bash test tooling
      run: sudo apt-get install bats

    - name: Install jsonschema tooling
      run: pip install jsonschema

    - name: Run tests
      run: run-tests.sh
