name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Bash test tooling
      run: sudo apt-get install bats

    - name: Download justify schema validator
      run: wget -q "https://github.com/leadpony/justify/releases/download/v2.1.0/justify-cli-2.1.0.tar.gz" -O justify-cli-2.1.0.tar.gz

    - name: Install justify schema validator
      run: | 
        tar xzf justify-cli-2.1.0.tar.gz
        ln -s justify-cli/justify justify
        ln -s justify-cli/lib lib

    - name: Run tests
      run: ./run-tests.sh
